"""Shared inventory for Batch A content quarantine."""

BLOG_SLUGS = [
    "a-home-care-plan-thats-all-about-you",
    "boosting-senior-safety-with-light-housekeeping",
    "elderly-comfort-optimizing-home-environments",
    "empathy-in-aging-nurturing-elderly-mental-health",
    "enhancing-quality-of-life-with-personal-home-care",
    "enhancing-senior-living-with-personal-assistance",
    "ensuring-home-care-safety-essential-tips",
    "ensuring-medication-adherence-for-better-health",
    "home-care-your-partner-in-aging-at-home",
    "home-nursing-care-key-services-you-need",
    "how-geriatric-care-improves-life-quality",
    "managing-medications-for-elderly-care",
    "medication-management-tips-for-home-health-aides",
    "nutrition-essentials-for-elderly-care",
    "preventing-falls-safe-homes-for-seniors",
    "promoting-wellness-in-senior-homes",
    "senior-wellness-holistic-home-care-tips",
    "the-benefits-personal-assistance-services",
    "the-holistic-approach-of-modern-home-care-agencies",
    "the-positive-impact-of-companionship-on-senior-health",
    "tips-for-choosing-the-right-home-care-provider",
    "understanding-medicaid-for-home-care-services",
    "unveiling-nursing-care-plans-a-comprehensive-guide",
    "why-home-care-is-essential-for-veterans-health",
    "home-care-blog-page-2",
    "home-care-blog-page-3",
    "home-care-blog-page-4",
    "home-care-blog-page-5",
]
